# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/view_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewControl(object):
    def setupUi(self, ViewControl):
        ViewControl.setObjectName("ViewControl")
        ViewControl.resize(1114, 867)
        self.groupBox = QtWidgets.QGroupBox(ViewControl)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 521, 281))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 521, 260))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_x = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.verticalLayout.addWidget(self.label_x)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.horizontal_slider_x = QtWidgets.QSlider(self.layoutWidget)
        self.horizontal_slider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_x.setObjectName("horizontal_slider_x")
        self.verticalLayout.addWidget(self.horizontal_slider_x)
        self.label_y = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.verticalLayout.addWidget(self.label_y)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout.addWidget(self.spinBox_2)
        self.horizontal_slider_y = QtWidgets.QSlider(self.layoutWidget)
        self.horizontal_slider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_y.setObjectName("horizontal_slider_y")
        self.verticalLayout.addWidget(self.horizontal_slider_y)
        self.label_z = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_z.setFont(font)
        self.label_z.setObjectName("label_z")
        self.verticalLayout.addWidget(self.label_z)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout.addWidget(self.spinBox_3)
        self.horizontal_slider_z = QtWidgets.QSlider(self.layoutWidget)
        self.horizontal_slider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_slider_z.setObjectName("horizontal_slider_z")
        self.verticalLayout.addWidget(self.horizontal_slider_z)

        self.retranslateUi(ViewControl)
        self.horizontal_slider_z.valueChanged['int'].connect(self.spinBox_3.setValue) # type: ignore
        self.horizontal_slider_y.sliderMoved['int'].connect(self.spinBox_2.setValue) # type: ignore
        self.horizontal_slider_y.valueChanged['int'].connect(self.spinBox_2.setValue) # type: ignore
        self.horizontal_slider_x.valueChanged['int'].connect(self.spinBox.setValue) # type: ignore
        self.spinBox_3.valueChanged['int'].connect(self.horizontal_slider_z.setValue) # type: ignore
        self.horizontal_slider_z.sliderMoved['int'].connect(self.spinBox_3.setValue) # type: ignore
        self.horizontal_slider_x.sliderMoved['int'].connect(self.spinBox.setValue) # type: ignore
        self.spinBox_2.valueChanged['int'].connect(self.horizontal_slider_y.setValue) # type: ignore
        self.spinBox.valueChanged['int'].connect(self.horizontal_slider_x.setValue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ViewControl)

    def retranslateUi(self, ViewControl):
        _translate = QtCore.QCoreApplication.translate
        ViewControl.setWindowTitle(_translate("ViewControl", "Form"))
        self.groupBox.setTitle(_translate("ViewControl", "GroupBox"))
        self.label_x.setText(_translate("ViewControl", "X-plane"))
        self.label_y.setText(_translate("ViewControl", "Y-plane"))
        self.label_z.setText(_translate("ViewControl", "Z-plane"))
